### ISSUE TITLE
ModuleNotFoundError: No module named 'r3det.datasets.rotate'

### ISSUE THREAD

**Issue by ghost** [SJTU-Thinklab-Det/r3det-pytorch#3]
>>> import r3det
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/amax/WorkSpace/liu/R3Det/r3det/__init__.py", line 5, in <module>
    from .datasets import *  # noqa: F401, F403
  File "/home/amax/WorkSpace/liu/R3Det/r3det/datasets/__init__.py", line 3, in <module>
    from .rotate import ROTATEDataset  # noqa: F401, F403
ModuleNotFoundError: No module named 'r3det.datasets.rotate'

Is there any file not uploaded？

**Comment by zytx121** [comment]
Thanks for your reply, we will fix it.
