### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ggzjg** [SJTU-Thinklab-Det/r3det-pytorch#6]
when I run the  'python tools/split/img_split.py --base_json \
       tools/split/split_configs/split_configs/dota1_0/ss_trainval.json'
output the error

TypeError: _nonzero_dispatcher() got an unexpected keyword argument 'as_tuple'

**Comment by sylarwcy** [comment]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/sylar/miniconda3/envs/r3det-n/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/sylar/miniconda3/envs/r3det-n/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/wcy/RotationDetection/code/r3det-pytorch-main/tools/split/img_split.py", line 310, in single_split
    window_anns = get_window_obj(info, windows, iof_thr)
  File "/home/wcy/RotationDetection/code/r3det-pytorch-main/tools/split/img_split.py", line 226, in get_window_obj
    iofs = bbox_overlaps_iof(bboxes, windows)  # 计算旋转框和划窗的iou
  File "/home/wcy/RotationDetection/code/r3det-pytorch-main/tools/split/img_split.py", line 212, in bbox_overlaps_iof
    for p in zip(*np.nonzero(h_overlaps, as_tuple=False)):
  File "<__array_function__ internals>", line 4, in nonzero

TypeError: _nonzero_dispatcher() got an unexpected keyword argument 'as_tuple'

**Comment by zytx121** [comment]
Sorry, we have fixed this bug now.

**Comment by ggzjg** [comment]
> thanks,thast's right！
