### ISSUE TITLE
train Error

### ISSUE THREAD

**Issue by ggzjg** [SJTU-Thinklab-Det/r3det-pytorch#8]
(open-mmlab) junjzhan@junjzhan-Super-Server:~/zhao_jg/code/r3det-pytorch-main$ CUDA_VISIBLE_DEVICES=0 PORT=29500 ./tools/dist_train.sh configs/rretinanet/rretinanet_obb_r50_fpn_1x_dota_v3.py 1
Traceback (most recent call last):
  File "/home/junjzhan/zhao_jg/code/r3det-pytorch-main/./tools/train.py", line 20, in <module>
    import r3det  # noqa: F401
  File "/home/junjzhan/zhao_jg/code/r3det-pytorch-main/r3det/__init__.py", line 4, in <module>
    from .core import *  # noqa: F401, F403
  File "/home/junjzhan/zhao_jg/code/r3det-pytorch-main/r3det/core/__init__.py", line 2, in <module>
    from .bbox import *  # noqa: F401, F403
  File "/home/junjzhan/zhao_jg/code/r3det-pytorch-main/r3det/core/bbox/__init__.py", line 2, in <module>
    from .iou_calculators import (RBboxOverlaps2D_v1, RBboxOverlaps2D_v2,
  File "/home/junjzhan/zhao_jg/code/r3det-pytorch-main/r3det/core/bbox/iou_calculators/__init__.py", line 1, in <module>
    from .rotate_iou2d_calculator import (RBboxOverlaps2D_v1, RBboxOverlaps2D_v2,
  File "/home/junjzhan/zhao_jg/code/r3det-pytorch-main/r3det/core/bbox/iou_calculators/rotate_iou2d_calculator.py", line 4, in <module>
    from r3det.ops import obb_overlaps, rbbox_iou
  File "/home/junjzhan/zhao_jg/code/r3det-pytorch-main/r3det/ops/__init__.py", line 1, in <module>
    from .box_iou_rotated import obb_overlaps
  File "/home/junjzhan/zhao_jg/code/r3det-pytorch-main/r3det/ops/box_iou_rotated/__init__.py", line 1, in <module>
    from .box_iou_rotated_wrapper import obb_overlaps  # noqa: F401, F403
  File "/home/junjzhan/zhao_jg/code/r3det-pytorch-main/r3det/ops/box_iou_rotated/box_iou_rotated_wrapper.py", line 4, in <module>
    from ..convex import convex_sort
  File "/home/junjzhan/zhao_jg/code/r3det-pytorch-main/r3det/ops/convex/__init__.py", line 1, in <module>
    from .convex_wrapper import convex_sort  # noqa: F401, F403
  File "/home/junjzhan/zhao_jg/code/r3det-pytorch-main/r3det/ops/convex/convex_wrapper.py", line 3, in <module>
    from . import convex_ext
ImportError: cannot import name 'convex_ext' from partially initialized module 'r3det.ops.convex' (most likely due to a circular import) (/home/junjzhan/zhao_jg/code/r3det-pytorch-main/r3det/ops/convex/__init__.py)
Traceback (most recent call last):
  File "/home/junjzhan/rogers/libraries/anaconda3/envs/open-mmlab/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/junjzhan/rogers/libraries/anaconda3/envs/open-mmlab/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/junjzhan/rogers/libraries/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/junjzhan/rogers/libraries/anaconda3/envs/open-mmlab/lib/python3.9/site-packages/torch/distributed/launch.py", line 255, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/home/junjzhan/rogers/libraries/anaconda3/envs/open-mmlab/bin/python', '-u', './tools/train.py', '--local_rank=0', 'configs/rretinanet/rretinanet_obb_r50_fpn_1x_dota_v3.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

**Comment by ggzjg** [comment]
it is import error,what should I do ?

**Comment by zytx121** [comment]
It looks like the `convex_sort` didn't compile successfully, Please execute `pip install -v -e .` again and check whether there are errors in the log.

**Comment by ggzjg** [comment]
thank you very much!!!! you just like my teacher.
